name: publish

on:
    release:
      types: [published]

jobs:
    make_sdist:
        name: Make SDist and wheel
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install build
              run: pip install build

            - name: Build SDist
              run: python -m build --sdist

            - name: Build wheel
              run: python -m build --wheel

            - uses: actions/upload-artifact@v4
              with:
                path: dist/*

    upload_on_pypi:
        needs: [make_sdist]
        environment: pypi
        permissions:
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: artifact
                path: dist

            - uses: pypa/gh-action-pypi-publish@release/v1
              with:
                repository-url: https://test.pypi.org/legacy/
